//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFW_MVC_APP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int ItemId { get; set; }

        [Required]
        public string ItemName { get; set; }
        
        [Required]
        public decimal Price { get; set; }

        [Required] 
        public string Image_URL { get; set; }
    }
}
